### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by patrickrodee** [PrestonR/actually#6]
Hello

I am very serious devloper who use this project. I need TypeScript definitions please.

Thanks you

**Comment by PrestonR** [comment]
How much types crypt, very many?

**Comment by patrickrodee** [comment]
Yes. Such an obvious question. I do not understand why you ask me such
obvious things.

**Comment by PrestonR** [comment]
Will send definitions actually of types crypt with reasons

**Comment by patrickrodee** [comment]
Plz do quick I need for my very important project thanks

**Comment by alexhgian** [comment]
We will have scripts of typed by Q4 of 2020. Require a major refactor.

**Comment by patrickrodee** [comment]
No I don’t think you understand that I need types now plz so I can launch
my very important project. If u cant add type defnitions soon I’ll have to
uses a different project like `really` because it’s clear ur not committed
to ur users sorry if that’s harsh but it’s true :/

**Comment by mirgags** [comment]
I have many Moments.  Plz help you with my setTimeout(0) should seems to work but dont know howwhy.  Ur welcome and thx in advance @patrickrodee Do you agree my think?

**Comment by alexhgian** [comment]
@patrickrodee we finally did it actually with help of 100 developers.

**Comment by alexhgian** [comment]
merged #7

**Comment by patrickrodee** [comment]
thanks you and yes i agree @mirgags `setTimeout` is very powerful feature of JS. you can read more about it here https://help.adobe.com/en_US/AS2LCR/Flash_10.0/help.html?content=00000602.html

**Comment by davidsargent** [comment]
@mirgags hi led developer here. no need worry. `setTimout` is magic good. but why awesome when you can have amazing? look at soon `actually.justWork(true)` in new months!

@patrickrodee thanks much. valuable feedback community appreciate.

**Comment by davidsargent** [comment]
@mirgags hi led developer here. no need worry. `setTimout` is magic good. but why awesome when you can have amazing? look at soon `actually.justWork(true, 0)` in new months!

@patrickrodee thanks much. valuable feedback community appreciate.

**Comment by mirgags** [comment]
@patrickrodee yes thxs you but I have much experiences in ACTIONSCRIPT but asking plz favor for JAAVASCRIPT that is differnt scripting language plz see comment from before

@davidsargent please complete also feature method actually.justWork(true, window.XMLHttpRequest) URGENT nedd

**Comment by davidsargent** [comment]
@mirgags that will be companion peace. for now, help on the horizon: https://github.com/PrestonR/actually/pull/8

on 3rd thought, `setTimeout` wants function as first parameter. boo. I make `actually.justWork` bettor by default: `actually.justWork()` same as `actually.justWork(true, 0)`. even bettar, argument order not matter now :>

`actually.justWork(fn, 2000)` same as `actually.justWork(2000, fn)` same as `actually.justWork('you think', 2000, 'this not work', fn, 'but it do')`
